import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import LinkToCart from '@/components/cart/navigation';
import { RootProviders } from '@/data/providers/root-provider';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProviders>
          <header className="flex w-full">
            <nav className="container flex justify-between p-4">
              <Link href="/">Home</Link>
              <LinkToCart />
            </nav>
          </header>
          {children}
        </RootProviders>
      </body>
    </html>
  );
}
